# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('logIn', models.BooleanField(default=False)),
            ],
        ),
    ]
