# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181216_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('op1', models.TextField()),
                ('op2', models.TextField()),
                ('op3', models.TextField()),
                ('op4', models.TextField()),
                ('answer', models.CharField(choices=[('op1', 'option1'), ('op2', 'option2'), ('op3', 'option3'), ('op4', 'option4')], max_length=10)),
            ],
        ),
    ]
